"""Deterministic artifact generation from a V3 manifest.

Every file is a pure function of the manifest (`artifact.json`) and the artifact kind, so the independent verifier
can regenerate the whole bundle and require byte equality. That is also what makes running the generated tests
safe: the verifier only executes code it would have generated itself.

Relations are compiled from validated expression trees into plain Python arithmetic. Units were checked when the
specification was compiled (V2 expressions have no unit conversions, only exact unit agreement), so plain floats
reproduce V2's comparison exactly, with the same tolerance.
"""

from __future__ import annotations

import json
from typing import Any, Mapping

from ..discovery.errors import DiscoveryError
from ..discovery.expr import EQ_TOLERANCE, Relation, env_of, from_json
from .errors import ProductionError

CODEGEN_VERSION = "production.codegen/1"
ACCEPTANCE_SCHEMA = "lofgren.acceptance/1"
PLAN_SCHEMA = "lofgren.artifact-plan/1"
_INFIX = {"add": "+", "sub": "-", "mul": "*", "div": "/"}

# Files each kind contains, in order. Every kind carries the manifest, the plan and the machine-readable checks.
KIND_FILES = {
    "structured_bundle": ("artifact.json", "plan.json", "acceptance.json", "README.md", "artifact.py",
                          "test_artifact.py"),
    "markdown": ("artifact.json", "plan.json", "acceptance.json", "README.md"),
    "python_module": ("artifact.json", "plan.json", "acceptance.json", "artifact.py", "test_artifact.py"),
}
PROBE_SCALES = (0.0, -1.0, 0.5, 2.0)  # each variable a check reads is rescaled, one at a time
MEDIA_TYPES = {".json": "application/json", ".md": "text/markdown", ".py": "text/x-python"}
EXECUTABLE_KINDS = ("structured_bundle", "python_module")


def expr_source(node: Any) -> str:
    """Python source for one validated expression tree. Variables read from the mapping `V`."""
    e = from_json(node)  # validates shape, names, numbers, depth and size
    return _src(e.to_json())


def _src(n: Mapping[str, Any]) -> str:
    op = n["op"]
    if op == "const":
        return repr(float(n["value"]))
    if op == "var":
        return f"V[{n['name']!r}]"
    args = [_src(a) for a in n.get("args", [])]
    if op in _INFIX:
        return f"({args[0]} {_INFIX[op]} {args[1]})"
    if op in ("min", "max"):
        return f"{op}({args[0]}, {args[1]})"
    if op == "neg":
        return f"(-{args[0]})"
    if op == "pow":
        return f"({args[0]} ** {int(n['exponent'])})"
    raise ProductionError(f"cannot generate code for expression op {op!r}")


def relation_source(relation: Mapping[str, Any]) -> list[str]:
    """Body lines of a check function: True when the relation holds, with V2's tolerance rule."""
    lines = [f"lhs = {expr_source(relation['lhs'])}", f"rhs = {expr_source(relation['rhs'])}"]
    op = relation["op"]
    if op == ">=":
        lines.append("return lhs - rhs >= -TOLERANCE")
    elif op == "<=":
        lines.append("return rhs - lhs >= -TOLERANCE")
    elif op == "==":
        lines.append("return abs(lhs - rhs) <= TOLERANCE * max(1.0, abs(lhs), abs(rhs))")
    else:
        raise ProductionError(f"unsupported relation operator {op!r}")
    return lines


def _json(value: Any) -> str:
    return json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def _literal(value: Any) -> str:
    return repr(json.loads(json.dumps(value, sort_keys=True, ensure_ascii=False, allow_nan=False)))


def python_module(m: Mapping[str, Any]) -> str:
    out = [
        '"""Generated by Lofgren Intelligence V3 Production Intelligence (' + CODEGEN_VERSION + ').',
        "",
        "A deterministic, inspectable implementation of the selected candidate: its typed values and an executable",
        "check for every acceptance criterion and evaluable constraint. Regenerated byte for byte by the verifier.",
        '"""',
        "",
        f"ARTIFACT = {_literal(m)}",
        "",
        f"VALUES = {_literal({k: v['value'] for k, v in m['values'].items()})}",
        f"UNITS = {_literal({k: v['unit'] for k, v in m['values'].items()})}",
        f"TOLERANCE = {EQ_TOLERANCE!r}",
        "",
        "",
        "def describe():",
        "    return ARTIFACT.copy()",
    ]
    for i, c in enumerate(m["checks"], 1):
        out += ["", "", f"def _check_{i:03d}(V):", f"    # {c['requirement_id']} ({c['kind']})"]
        out += ["    " + line for line in relation_source(c["relation"])]
    out += ["", "", "CHECKS = ("]
    for i, c in enumerate(m["checks"], 1):
        out.append(f"    ({c['requirement_id']!r}, {c['kind']!r}, {c['name']!r}, _check_{i:03d}),")
    out += [
        ")",
        "",
        "",
        "def check_all(values=None):",
        '    """Requirement id -> whether its check holds, over VALUES or the given values."""',
        "    V = VALUES if values is None else values",
        "    return {req: fn(V) for req, _kind, _name, fn in CHECKS}",
        "",
    ]
    return "\n".join(out)


def test_module(m: Mapping[str, Any]) -> str:
    out = [
        '"""Acceptance tests generated by Lofgren Intelligence V3 (' + CODEGEN_VERSION + ').',
        "",
        "Run from the artifact directory: python -m unittest -v test_artifact",
        '"""',
        "",
        "import json",
        "import pathlib",
        "import unittest",
        "",
        "import artifact",
        "",
        'HERE = pathlib.Path(__file__).resolve().parent',
        "",
        "",
        "def _load(name):",
        '    return json.loads((HERE / name).read_text(encoding="utf-8"))',
        "",
        "",
        "class AcceptanceTests(unittest.TestCase):",
    ]
    if not m["checks"]:
        out += ["    pass"]
    for i, c in enumerate(m["checks"]):
        name = "test_" + c["requirement_id"].replace("-", "_")
        out += [f"    def {name}(self):", f"        req, kind, label, fn = artifact.CHECKS[{i}]",
                f"        self.assertEqual(req, {c['requirement_id']!r})",
                "        self.assertTrue(fn(artifact.VALUES), f'{req} {kind} {label!r} does not hold')", ""]
    out += [
        "",
        "class IntegrityTests(unittest.TestCase):",
        "    def test_module_matches_manifest(self):",
        '        self.assertEqual(artifact.ARTIFACT, _load("artifact.json"))',
        "",
        "    def test_values_match_manifest(self):",
        '        values = _load("artifact.json")["values"]',
        "        self.assertEqual(artifact.VALUES, {k: v['value'] for k, v in values.items()})",
        "",
        "    def test_checks_match_acceptance_file(self):",
        '        checks = _load("acceptance.json")["checks"]',
        "        self.assertEqual([c[0] for c in artifact.CHECKS], [c['requirement_id'] for c in checks])",
        "",
        "    def test_checks_reproduce_reference_probes(self):",
        '        for probe in _load("acceptance.json")["probes"]:',
        "            got = artifact.check_all(probe['values'])",
        "            self.assertEqual(got, probe['expected'], (probe['variable'], probe['scale']))",
        "",
        "    def test_every_requirement_is_planned(self):",
        '        required = {r["id"] for r in _load("artifact.json")["requirements"]}',
        '        covered = {req for f in _load("plan.json")["files"] for req in f["covers"]}',
        "        self.assertEqual(required - covered, set())",
        "",
        "",
        'if __name__ == "__main__":',
        "    unittest.main()",
        "",
    ]
    return "\n".join(out)


def expected_test_count(m: Mapping[str, Any]) -> int:
    return len(m["checks"]) + 5


def probes(m: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Reference vectors: perturbed inputs with each check's expected result from V2's own evaluator.

    The generated tests must reproduce every expected result, including the ones where a check must fail, so a
    generated check can be neither unfaithful to V2 nor vacuously true. Vectors V2 cannot evaluate are skipped.
    """
    base = {k: v["value"] for k, v in m["values"].items()}
    units = {k: v["unit"] for k, v in m["values"].items()}
    relations = [(c["requirement_id"], Relation.from_json(c["relation"])) for c in m["checks"]]
    used = sorted(set().union(*(r.variables() for _, r in relations))) if relations else []
    out = []
    for name in used:
        for scale in PROBE_SCALES:
            values = {**base, name: base[name] * scale}
            if values == base:
                continue
            try:
                env = env_of({k: (v, units[k]) for k, v in values.items()})
                expected = {rid: bool(r.check(env).satisfied) for rid, r in relations}
            except (DiscoveryError, ZeroDivisionError, OverflowError):
                continue
            out.append({"variable": name, "scale": scale, "values": values, "expected": expected})
    return out


def falsified(m: Mapping[str, Any]) -> list[str]:
    """Checks that at least one probe makes fail (the others are reported as not falsified by the probes)."""
    return sorted({rid for p in probes(m) for rid, ok in p["expected"].items() if not ok})


def acceptance_json(m: Mapping[str, Any]) -> str:
    return _json({"schema": ACCEPTANCE_SCHEMA, "tolerance": EQ_TOLERANCE, "checks": m["checks"],
                  "probes": probes(m), "falsified_by_probes": falsified(m)})


def plan(m: Mapping[str, Any], kind: str) -> dict[str, Any]:
    """Which file satisfies which requirement. Every requirement must be covered by at least one file."""
    paths = KIND_FILES[kind]
    reqs = m["requirements"]
    by_kind = {k: [r["id"] for r in reqs if r["kind"] == k] for k in
               ("specification", "outcome", "acceptance", "constraint", "test", "dependency")}
    checked = [c["requirement_id"] for c in m["checks"]]
    roles = {
        "artifact.json": ("manifest", by_kind["specification"] + by_kind["outcome"] + by_kind["test"]
                          + by_kind["dependency"] + [r for r in by_kind["constraint"] if r not in checked]),
        "acceptance.json": ("machine-readable checks", checked),
        "README.md": ("human-readable specification", [r["id"] for r in reqs]),
        "artifact.py": ("implementation", by_kind["specification"] + by_kind["outcome"] + checked),
        "test_artifact.py": ("executable acceptance tests", checked),
    }
    return {"schema": PLAN_SCHEMA, "kind": kind, "codegen": CODEGEN_VERSION,
            "files": [{"path": p, "role": roles[p][0], "covers": roles[p][1]} for p in paths if p != "plan.json"]}


def readme(m: Mapping[str, Any], kind: str) -> str:
    cand = m["selected_candidate"]
    lines = ["# Lofgren Intelligence V3 Artifact", "", f"Objective: {m['objective']}", "",
             f"Selected candidate: {cand.get('description', cand.get('id'))}", "", "## Specifications", ""]
    for name, v in m["values"].items():
        lines.append(f"- {name}: {v['value']:g} {v['unit']}".rstrip())
    lines += ["", "## Requirements", "", "| Id | Kind | Requirement |", "| --- | --- | --- |"]
    for r in m["requirements"]:
        lines.append(f"| {r['id']} | {r['kind']} | {r['detail'].replace('|', '/')} |")
    lines += ["", "## Acceptance criteria", ""]
    hit = set(falsified(m))
    for c in m["checks"]:
        note = "" if c["requirement_id"] in hit else " (no probe makes this check fail; review it)"
        lines.append(f"- {c['requirement_id']} ({c['kind']}): {c['name']}{note}")
    open_items = [r for r in m["requirements"] if r["kind"] in ("test", "dependency")]
    if open_items:
        lines += ["", "## Open verification work (not executable here)", ""]
        lines += [f"- {r['id']}: {r['detail']}" for r in open_items]
    if kind in EXECUTABLE_KINDS:
        lines += ["", "## Tests", "", "Run `python -m unittest -v test_artifact` in this directory."]
    lines += ["", "## Provenance", "", f"- Discovery: {m['source_discovery_id']}",
              f"- Discovery fingerprint: {m['source_discovery_fingerprint']}",
              "- Simulated outcomes are predictions, not observations. Nothing here is authorized for execution.", ""]
    return "\n".join(lines)


def generate(m: Mapping[str, Any], kind: str) -> list[tuple[str, str, str]]:
    """(path, media type, content) for every file of the kind, from the manifest alone."""
    if kind not in KIND_FILES:
        raise ProductionError(f"unsupported artifact kind {kind!r}")
    m = json.loads(json.dumps(m, sort_keys=True, ensure_ascii=False, allow_nan=False))  # one canonical key order
    makers = {
        "artifact.json": lambda: _json(m),
        "plan.json": lambda: _json(plan(m, kind)),
        "acceptance.json": lambda: acceptance_json(m),
        "README.md": lambda: readme(m, kind),
        "artifact.py": lambda: python_module(m),
        "test_artifact.py": lambda: test_module(m),
    }
    return [(p, MEDIA_TYPES["." + p.rsplit(".", 1)[1]], makers[p]()) for p in KIND_FILES[kind]]
